export const Endpoints = {
  PRAYER_TIMES: '/api/prayer-times',
  TODAY_HIJRI_DATE: '/api/today-hijri',
  HADEES_OF_THE_DAY: '/api/hadith/random',
  DUA_OF_THE_DAY: '/api/duas/random',
  ALL_DUAS: '/api/duas',
  VERSE_OF_THE_DAY: '/api/quran/random',
  NOMINATIM_SEARCH: 'https://nominatim.openstreetmap.org/search',
  HEART_BEAT: '/api/heart-beat',
  ACTIVITY_STATS: '/api/activity-stats',
  SURAHS_METADATA: '/api/quran/surahs',
  SURAH_BY_NUMBER: '/api/quran/surah/',
  quran: {
    surahList: 'https://api.alquran.cloud/v1/surah',
    surahDetail: (number: number) =>
      `https://api.alquran.cloud/v1/surah/${number}/editions/quran-uthmani,en.sahih,en.transliteration,ar.alafasy,ur.jalandhry,hi.hindi,ur.khan`,
  },
  SAVE_DUA_BOOKMARK_IDS: '/api/save-dua-bookmark-ids',
  GET_DUA_BOOKMARK_IDS: '/api/get-dua-bookmark-ids',
  HADITHS_COLLECTIONS: '/api/hadith/collections',
  HADITHS_BY_COLLECTION: '/api/hadith/',
  HADITHS_SEARCH: '/api/hadith/search',
  GET_VIDEOS: '/api/get-videos',
  SEND_PUSH: '/api/send-push',
  SAVE_SUBSCRIPTION: '/api/save-subscription',
  ACK_PRAYER: '/api/ack-prayer',
};
